Add shell loader to list of utility loaders
d3viant0ne/awesome-webpack pull request #102
Opened 2018-05-04 20:39 UTC by localjo

Adds [`shell-loader`](https://github.com/localjo/shell-loader) to the list of utility loaders. This loader allows you to run arbitrary shell scripts on files. It's useful as a shim for preprocessors that don't have dedicated loaders.

2018-06-09 13:10 UTC, evilebottnawi commented
@localjo just for interesting, why not use `execa`? It is stable and very good package for run child processes

2018-06-09 13:16 UTC, localjo commented
@evilebottnawi I don't think `execa` is a Webpack loader. It does something completely different than `shell-loader`.

2018-06-09 13:21 UTC, alexander-akait commented
@localjo looks i was misleading, look on https://github.com/sindresorhus/execa

2018-06-09 15:13 UTC, localjo commented
`execa` is not related to Webpack, but if it works for your needs, that's great. ☺️

2019-02-05 08:28 UTC, alexander-akait requested changes

2019-02-05 08:28 UTC, alexander-akait commented on README.md
> +-- *Maintainer*: `Jo Sprague` [![Github][githubicon]](https://github.com/localjo)
Please format this in one line, look on other examples

2019-02-05 17:08 UTC, localjo commented
Closing in favor of #130

2019-02-05 17:08 UTC, closed without merging