Add svg-sprite-webpack-plugin to Plugins section
d3viant0ne/awesome-webpack pull request #43
Opened 2017-02-03 22:06 UTC by jetpacmonkey

[svg-sprite-webpack-plugin](https://github.com/TodayTix/svg-sprite-webpack-plugin) is a plugin/loader we recently open-sourced. It allows you to `import` an SVG, and extracts it into an external, cacheable sprite file, returning the full href for the `<use>` tag from the loader.

## Given:

**myIcon.svg**
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="10px" height="10px" viewBox="0 0 24 10" version="1.1">
  <line x1="0" y1="0" x2="10" y2="10"></line>
</svg>
```

**myReactIconThing.js**
```jsx
import React from 'react';
import myIcon from './myIcon.svg';

export default function() {
  return <svg><use href={myIcon} /></svg>;
}
```

## Renders:

(assuming the extracted icons have an md5 hash of `abcd1234`)

**In browser**
```html
<svg><use href="/static/icons-abcd1234.svg#myIcon"></use></svg>
```

**In `icons-abcd1234.svg`**
```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <symbol id="myIcon" width="10px" height="10px" viewBox="0 0 24 10">
    <line x1="0" y1="0" x2="10" y2="10"></line>
  </symbol>
</svg>
```

2017-02-03 22:33 UTC, kentcdodds requested changes

2017-02-03 22:33 UTC, kentcdodds commented on README.md
> +- [SVG Sprite Webpack Plugin](https://github.com/TodayTix/svg-sprite-webpack-plugin) - Plugin/loader for SVG sprites and `<use>`-based icon systems. -- *Maintainer*: `Jeremy Tice` ([`TodayTix`](https
I know that we normally prefer these items take up only a single line. Could you shorten the description a bit? Remove the redundant "Plugin/loader" bit I think is a good start.

2017-02-03 22:33 UTC, kentcdodds commented
Cool plugin!

2017-02-03 22:40 UTC, d3viant0ne commented on README.md
> +- [SVG Sprite Webpack Plugin](https://github.com/TodayTix/svg-sprite-webpack-plugin) - Plugin/loader for SVG sprites and `<use>`-based icon systems. -- *Maintainer*: `Jeremy Tice` ([`TodayTix`](https
Read prefer as hard and fast rule, please no word wrap.

2017-02-04 17:52 UTC, jetpacmonkey commented
@kentcdodds @d3viant0ne is that better?

2017-02-04 21:35 UTC, kentcdodds approved these changes
LGTM!

2017-02-04 21:35 UTC, merged